### PR TITLE
Auto-publish on PyPI and test test the tarball

### PR DESCRIPTION
**Pull request by ocefpaf**
Not ready for review yet. Only merge after #173 

Closes https://github.com/python-windrose/windrose/issues/110

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Pypi invite sent https://pypi.org/manage/project/windrose/collaboration/

Accepted and added the upload token to the secrets here. The sdist and wheel tests are passing but an upload to PyPI only happen if we have a tag. See https://github.com/python-windrose/windrose/runs/6292093461?check_suite_focus=true

I'll try to get to a new release that has the fix for https://github.com/python-windrose/windrose/issues/170 later today.

**Comment by scls19fr** [comment]
You probably should enable 2FA on your Pypi account.
I personnally use Authy https://authy.com/ but hardware key seems to also be supported (ie Yubikey or any other U2F/FIDO2 keys)

**Comment by scls19fr** [comment]
you need to store you recovery keys and Pypi ask one key before adding your 2FA application code (to ensure that you keep recovery keys somewhere)

**Comment by scls19fr** [comment]
That's why I prefer Authy over Google Auth... Because of Sync accross several devices

**Comment by ocefpaf** [comment]
> That's why I prefer Authy over Google Auth... Because of Sync accross several devices

I use it in conda-forge but never crossed my mind to use it for my own accounts. I'll give it a go. Thanks!

PS: this one is ready to go.

**Pull request merged**
