### PR TITLE
Fix issue with matplotlib 3.6.0

### LINKED ISSUE #190: pacman-shaped wind roses
Hello, and first of all thanks for this great package.

I have installed the latest version and have some issues that I have not encountered before: the roses are not closed, and looks like a pacman, as it can be seen from the figure enclosed below.

```{python}
import windrose as wrose
ax = wrose.WindroseAxes.from_ax()
```
image

I show here a very simple plot, but the problem remains whenever I add some data.

Do you have any idea where does this problem comes from and how could I solve it ?

The following version are installed in a dedicated environment

> windrose             1.7.0
> matplotlib           3.6.0

### PR DESCRIPTION
**Pull request by ocefpaf**
This should work with mpl >=3 b/c too, I updated the minimum requirement.

Closes #190

### CODE REVIEW

**Comment by ocefpaf** [comment]
I'm converting this to draft for now b/c I want to add a simple regression test that compares images before we move forward.

**Comment by ocefpaf** [comment]
Without the fix here the tests capture 18 failures, all related to the "pacman" reported  #190:

Screenshot from 2022-09-20 14-47-34

@scls19fr this one is ready for review!

**Comment by tacaswell** [comment]
This fix may cause issues with older versions of Matplotilb, see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#axes-subclasses-should-override-clear-instead-of-cla

Looking at what cartopy does may be a good reference.

**Comment by ocefpaf** [comment]
> This fix may cause issues with older versions of Matplotilb, see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#axes-subclasses-should-override-clear-instead-of-cla
> 
> Looking at what cartopy does may be a good reference.

I tested with 3.5 but I'll test a bit more and pin mpl to a >= ver_that_work. Thanks!

**Pull request merged**
