### PR TITLE
Use pytest-mpl to check the images

### PR DESCRIPTION
**Pull request by ocefpaf**
@scls19fr this is a major refactor on the test and I hope it is OK. We need to catch issues like #190.

### CODE REVIEW

**Comment by ocefpaf** [comment]
This one is ready for review. When merged I'll unpin rebase #191 and unpin matplotlib to ensure we catch all the differences in the new version.

**Comment by scls19fr** [comment]
I just hope this kind of tests won't break too often.
Let's give it a try.

**Comment by scls19fr** [comment]
Lgtm

**Comment by ocefpaf** [comment]
> I just hope this kind of tests won't break too often.

I have the same concern but cartopy has been using pytest-mpl for a while and it seems quite robust. My local tests showed the "pacman" problem reported in #190 nicely. However, if things are too brittle we can dial back and use just a bare axes for the test with a allow_failure flag.

> Let's give it a try.

:+1:

**Pull request merged**
