### PR TITLE
Add option to specify radius steps

### PR DESCRIPTION
**Pull request by sspagnol**
Allow user to specify the steps at which radius circles and labels will be drawn as, and also sets the rmax value to be a multiple of rstep. So for example a call to plot_windrose(t, r, kind='bar', normed=True, blowto=False, rstep=5) will generate radii/labels of 5,10,15 etc. I don't know if this the best way to achieve this (that is should this be part of WindroseAxes constructor or just passed around in kwargs?), it just worked for my use case.

### CODE REVIEW

**Comment by scls19fr** [comment]
Thanks for this PR but it's generaly a best practice to first open an issue to explain the problem.
Then, create a PR which fix it (writing Closes #xyz where xyz is the number of issue)

**Comment by ocefpaf** [comment]
@sspagnol do you want to continue working in this? If so note that I rebased against our latest code tests. We need a test for this functionality and, if you can, add means for folks accessing it via the various plotting options.

**Comment by simonweppe** [comment]
Would be great to have that as an option @ocefpaf  !

**Comment by ocefpaf** [comment]
@simonweppe it seems that this PR is abandoned and needs some work/rebasing. Do you want to pick it up?

**Comment by jkittner** [comment]
Maybe I don't fully understand what your point is but doesn't this (`set_rgrids`) do exactly what you want?

```python

import pandas as pd
from windrose import WindroseAxes
import matplotlib.pyplot as plt

df = pd.DataFrame({
    'wind_dir': [360, 360, 360, 360, 360, 180, 180, 180, 180, 180],
    'wind_speed': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5,],
})

ax = WindroseAxes.from_ax()
ax.bar(df['wind_dir'], df['wind_speed'], normed=True, bins=[2, 3], calm_limit=2)
ax.set_legend()
rgrids = [0, 10, 20, 30, 40, 50]
ax.set_rgrids(rgrids, rgrids)
```

I think I'd rather add this to the documentation than to pass this through as yet another kwarg?

**Comment by sspagnol** [comment]
Sounds ok to me.

**Comment by simonweppe** [comment]
@jkittner  yep it does :) thank you very much

**Pull request closed without merging**
