### PR TITLE
[DOC] comply docstring with numpydoc

### PR DESCRIPTION
**Pull request by weber-s**
This PR make the docstring compatible with numpydoc, following this comment: https://github.com/python-windrose/windrose/commit/25d53a7f53cbfe95cd23a9f6127ad03a4ca3a0ef#commitcomment-28855901

There is also one improvement in the `legend` function and a inconsistency with `decimal_places`, which is not an argument of the legend function of matplotlib but a argument of the internal `get_labels` function.
This argument was in the kwarg, but with default value to 1 in the function (l 202.). I added it explicitly.

Thanks for this great tool!

### CODE REVIEW

**Comment by scls19fr** [comment]
PEP8 cleanup is required for this PR to be merged
See https://travis-ci.org/python-windrose/windrose/jobs/375221935#L781

**Comment by scls19fr** [comment]
Thanks Samüel for your nice contribution

**Comment by scls19fr** [comment]
Doc is build automatically and should be available at http://windrose.readthedocs.io/en/latest/?badge=latest

**Comment by weber-s** [comment]
Ok thank you for this module!

I may contribute a bit more in the next few weeks if I have time.

**Pull request merged**
