### PR TITLE
Bugs/117 deprecated function copy dedent

### PR DESCRIPTION
**Pull request by weber-s**
Should fix deprecated function spotted in #117.

### CODE REVIEW

**Comment by scls19fr** [comment]
Thanks @weber-s for your contribution

**Comment by ets86** [comment]
Hey there, I'm still stuck with the problem. I'm only getting started with python since i need it for a paper.

That what I'm writing:

`from windrose import WindroseAxes`

`import pandas as pd`
`import numpy as np`
`import matplotlib.pyplot as plt`
`import datetime`

And thats what I'm getting:

C:\Users\...\Anaconda\lib\site-packages\windrose\windrose.py:29: MatplotlibDeprecationWarning: 
The Appender class was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  addendum = docstring.Appender(msg, "\n\n")
C:\Users\...\Anaconda\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning: 
The copy_dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use docstring.copy() and cbook.dedent() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
C:\Users\...\Anaconda\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.getdoc() instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))
C:\Users\...\Anaconda\lib\site-packages\windrose\windrose.py:30: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  return lambda func: addendum(docstring.copy_dedent(base)(func))




I just downloaded python 3.7 (Win 10)

Maybe someone could try to help me using "easy" language

Thanks in advance

**Comment by weber-s** [comment]
Hei,

This PR has been merge, but no release has been done so far; Windrose is in version 1.6.7, but this patch is for version >1.6.7.

By the way, it's "only warning", not error... But if you want to remove them, you have to install windrose from the git source like that:

    pip install git+https://github.com/python-windrose/windrose

@scls19fr : do you plan to update the pypi version in order to incorporate the latest change?

**Comment by scls19fr** [comment]
I think this project will need some care.
Publish a last release which is compatible with Python 2.7
Drop Python 2.7 support
Publish a need release.
Anyone here interested in taking the lead to complete theses tasks?

**Comment by AndyLuckert** [comment]
The compatibility issue between matplotlib and windrose **came back as error** related to `AttributeError: module 'matplotlib.docstring' has no attribute 'Appender'`.

I've already commented on the prematurely closed issue:
https://github.com/python-windrose/windrose/issues/119#issuecomment-661115579

**Comment by Hossein-Madadi** [comment]
I had same problem yesterday, but the below link helped me to solve it.
https://stackoverflow.com/questions/42733194/subplot-of-windrose-in-matplotlib#answer-42734053:~:text=(b)%20adding%20a%20projection

**Pull request merged**
