### PR TITLE
Calm conditions

### PR DESCRIPTION
**Pull request by LionelR**
Set a calm_limit parameter for computing a calm_count/offset value from which a centred circle will be drawn. 
In response to #58

### CODE REVIEW

**Comment by scls19fr** [comment]
CI is now fixed
Could you update this PR?

**Comment by LionelR** [comment]
CI always complaints on flake8 :
1.02s$ flake8 --ignore=E501 windrose samples tests

windrose/windrose.py:132:37: E226 missing whitespace around arithmetic operator

windrose/windrose.py:302:50: E226 missing whitespace around arithmetic operator

windrose/windrose.py:302:54: E226 missing whitespace around arithmetic operator

windrose/windrose.py:318:29: E128 continuation line under-indented for visual indent

windrose/windrose.py:319:29: E128 continuation line under-indented for visual indent

windrose/windrose.py:320:29: E128 continuation line under-indented for visual indent

windrose/windrose.py:351:77: W291 trailing whitespace

windrose/windrose.py:404:77: W291 trailing whitespace

windrose/windrose.py:461:77: W291 trailing whitespace

windrose/windrose.py:524:77: W291 trailing whitespace

The command "flake8 --ignore=E501 windrose samples tests" exited with 1.

**Comment by scls19fr** [comment]
@LionelR Could you rebase?

**Comment by scls19fr** [comment]
Superseed by https://github.com/python-windrose/windrose/pull/102

**Pull request closed without merging**
